### ISSUE TITLE
Despadronização no menu da tela principal

### ISSUE THREAD

**Issue by diogomoreira** [recursivejr/sib#6]
Ao se logar na aplicação e ser apresentado a interface principal do sistema, os rótulos dos menus estão despadronizados, uns em negrito e outros não-negrito.

Papel utilizado: Bibliotecário

![screenshot from 2015-04-10 16 38 10](https://cloud.githubusercontent.com/assets/808759/7095400/8e1ca472-dfa0-11e4-838a-0e95d3218ce8.png)

**Comment by VictorHugoSRibeiro** [comment]
Concertado
